name: Backend CI/CD
on:
  push:
    branches: [ "main" ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run backend unit tests
        run: ./gradlew test

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build backend Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cineverse-backend:latest .

      - name: Push backend Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cineverse-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: Deploy on Contabo via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd cineverse-api/
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker compose pull cineverse-app
            docker compose up -d cineverse-app